<<<<<<< HEAD
# Generated by Django 5.2.8 on 2025-11-21 16:35
=======
# Generated by Django 5.2.8 on 2025-11-21 17:10
>>>>>>> perdidas-samuel

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('cultivos', '0001_initial'),
>>>>>>> perdidas-samuel
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_cosecha', models.DateField()),
                ('cantidad', models.FloatField()),
                ('descripcion', models.TextField(blank=True)),
                ('cultivo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cosechas.cultivo')),
=======
            name='Cosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cosecha', models.DateField()),
                ('cantidad_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calidad', models.CharField(blank=True, max_length=100, null=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosechas', to='cultivos.cultivo')),
>>>>>>> perdidas-samuel
            ],
        ),
    ]
