# Generated by Django 5.2.8 on 2025-11-21 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cultivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cosecha', models.DateField()),
                ('cantidad_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calidad', models.CharField(blank=True, max_length=100, null=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosechas', to='cultivos.cultivo')),
            ],
        ),
    ]
