# Generated by Django 5.2.8 on 2025-11-21 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cultivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perdida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('plaga', 'Plaga'), ('clima', 'Clima'), ('manejo', 'Manejo'), ('otro', 'Otro')], max_length=50)),
                ('causa', models.TextField()),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha', models.DateField()),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perdidas', to='cultivos.cultivo')),
            ],
        ),
    ]
