# Generated by Django 5.2.8 on 2025-11-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('maiz', 'Maíz'), ('trigo', 'Trigo'), ('arroz', 'Arroz'), ('frijol', 'Frijol'), ('otro', 'Otro')], max_length=50)),
                ('area_hectareas', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fecha_siembra', models.DateField()),
                ('productor', models.CharField(max_length=100)),
            ],
        ),
    ]
