<<<<<<< HEAD
# Generated by Django 5.2.8 on 2025-11-21 15:36

import django.db.models.deletion
=======
# Generated by Django 5.2.8 on 2025-11-21 17:03

>>>>>>> perdidas-samuel
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variedades', to='cultivos.cultivo')),
            ],
            options={
                'ordering': ['cultivo__nombre', 'nombre'],
                'unique_together': {('cultivo', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.CharField(max_length=80)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('cantidad_planeada', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unidad', models.CharField(default='kg', max_length=20)),
                ('estado', models.CharField(default='activo', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producciones', to='cultivos.variedad')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
                'unique_together': {('variedad', 'ciclo')},
            },
        ),
=======
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('maiz', 'Maíz'), ('trigo', 'Trigo'), ('arroz', 'Arroz'), ('frijol', 'Frijol'), ('otro', 'Otro')], max_length=50)),
                ('area_hectareas', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fecha_siembra', models.DateField()),
                ('productor', models.CharField(max_length=100)),
            ],
        ),
>>>>>>> perdidas-samuel
    ]
